// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.1
// source: types/uuid/uuid.proto

package uuid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UUID 包装类型，底层存储为 16 字节
// 字段名不可叫 value，否则 Go 结构体字段 Value 会与 driver.Valuer 的 Value() 方法冲突
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_types_uuid_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_types_uuid_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_types_uuid_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_types_uuid_uuid_proto protoreflect.FileDescriptor

const file_types_uuid_uuid_proto_rawDesc = "" +
	"\n" +
	"\x15types/uuid/uuid.proto\x12\x04uuid\"\x1a\n" +
	"\x04UUID\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB4Z2github.com/azicen/kratos-extension/types/uuid;uuidb\x06proto3"

var (
	file_types_uuid_uuid_proto_rawDescOnce sync.Once
	file_types_uuid_uuid_proto_rawDescData []byte
)

func file_types_uuid_uuid_proto_rawDescGZIP() []byte {
	file_types_uuid_uuid_proto_rawDescOnce.Do(func() {
		file_types_uuid_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_uuid_uuid_proto_rawDesc), len(file_types_uuid_uuid_proto_rawDesc)))
	})
	return file_types_uuid_uuid_proto_rawDescData
}

var file_types_uuid_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_uuid_uuid_proto_goTypes = []any{
	(*UUID)(nil), // 0: uuid.UUID
}
var file_types_uuid_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_uuid_uuid_proto_init() }
func file_types_uuid_uuid_proto_init() {
	if File_types_uuid_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_uuid_uuid_proto_rawDesc), len(file_types_uuid_uuid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_uuid_uuid_proto_goTypes,
		DependencyIndexes: file_types_uuid_uuid_proto_depIdxs,
		MessageInfos:      file_types_uuid_uuid_proto_msgTypes,
	}.Build()
	File_types_uuid_uuid_proto = out.File
	file_types_uuid_uuid_proto_goTypes = nil
	file_types_uuid_uuid_proto_depIdxs = nil
}
